source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.lug.ustc.edu.cn/wzios/WZPodSpecs.git'

platform:ios, '9.0'

use_frameworks!

target 'WZAlertViewController_Example' do
  pod 'WZAlertViewController', :path => '../'

  target 'WZAlertViewController_Tests' do
    inherit! :search_paths

    
  end
end
